### ISSUE TITLE
`opts_slurmR` not appearing in sbatch script

### ISSUE THREAD

**Issue by gregorypenn** [USCbiostats/slurmR#23]
Maybe I'm doing this wrong, but if so then I can't figure out how to do it right.

I'm using `opts_slurmR$set_opts()` to set options that I want to appear in the `#SBATCH` lines at the beginning of the job script. For example:

```
opts_slurmR$set_opts(partition="debug", `get-user-env` = "",  `mail-type` = "BEGIN, FAIL, END")
```

The options appear to have been set correctly, based on the output of `opts_slurmR` and `opts_slurmR$get_opts_job()`. However, they do not appear in `myjob.sh`. Any guidance would be appreciated.

**Comment by gregorypenn** [comment]
Of course I figured it out right after creating an issue. I needed the argument to `Slurm_lapply(sbatch_opt = opts_slurmR$get_opts_job())`

**Comment by gvegayon** [comment]
It actually seems like a bug! Thanks for flagging that out. I'll fix it asap.

**Comment by gvegayon** [comment]
This is now fixed in the master branch, along with other anoying buys. Will submit to CRAN soon
